export const AI_PRODUCTION_STAGES = [
  {
    id: 'strategy',
    order: 1,
    name: 'Chiến lược nội dung',
    agent: 'AI Strategy Lead',
    purpose: 'Chuyển mục tiêu kinh doanh thành chủ đề, chiến dịch, thông điệp và KPI rõ ràng.',
    inputs: ['Mục tiêu kinh doanh', 'Dịch vụ cần ưu tiên', 'Khách hàng mục tiêu', 'Khu vực triển khai'],
    outputs: ['Content brief', 'Trụ cột nội dung', 'KPI chiến dịch', 'Lịch nội dung sơ bộ'],
    gate: 'Con người duyệt brief trước khi sản xuất.',
  },
  {
    id: 'research',
    order: 2,
    name: 'Nghiên cứu & dữ liệu',
    agent: 'AI Researcher',
    purpose: 'Thu thập dữ liệu đầu vào, kiểm chứng thông tin và tìm góc nội dung có giá trị.',
    inputs: ['Content brief', 'Ảnh/video công trình', 'Thông số sản phẩm', 'Phản hồi khách hàng'],
    outputs: ['Research pack', 'Insight khách hàng', 'Từ khóa', 'Rủi ro thông tin cần xác minh'],
    gate: 'Không đưa dữ liệu chưa xác minh sang khâu viết bài.',
  },
  {
    id: 'copy',
    order: 3,
    name: 'Sản xuất nội dung gốc',
    agent: 'AI Copywriter',
    purpose: 'Viết bản nội dung gốc theo giọng thương hiệu và mục tiêu chuyển đổi.',
    inputs: ['Content brief', 'Research pack', 'Brand voice', 'CTA mặc định'],
    outputs: ['Bản nội dung chính', 'Tiêu đề', 'CTA', 'Hashtag đề xuất'],
    gate: 'Bản gốc phải đúng dịch vụ, đúng đối tượng và không phóng đại.',
  },
  {
    id: 'adapt',
    order: 4,
    name: 'Chuyển thể đa nền tảng',
    agent: 'AI Channel Editor',
    purpose: 'Tạo phiên bản riêng cho từng nền tảng thay vì đăng một nội dung giống nhau ở mọi nơi.',
    inputs: ['Bản nội dung chính', 'Nền tảng đích', 'Media', 'Giới hạn ký tự'],
    outputs: ['Facebook post', 'TikTok caption', 'YouTube metadata', 'Pinterest copy', 'Zalo copy'],
    gate: 'Mỗi phiên bản phải phù hợp định dạng và hành vi người dùng của nền tảng.',
  },
  {
    id: 'creative',
    order: 5,
    name: 'Điều phối hình ảnh & video',
    agent: 'AI Creative Producer',
    purpose: 'Tạo yêu cầu sản xuất hình ảnh/video theo đúng nội dung và nhận diện thương hiệu.',
    inputs: ['Nội dung đã chuyển thể', 'Ảnh nguồn', 'Kích thước nền tảng', 'Brand kit'],
    outputs: ['Creative brief', 'Prompt ảnh/video', 'Shot list', 'Danh sách kích thước xuất bản'],
    gate: 'Không tự ý thay đổi cấu tạo, vật liệu hoặc hiện trạng công trình.',
  },
  {
    id: 'quality',
    order: 6,
    name: 'Kiểm tra chất lượng',
    agent: 'AI Brand & QA Reviewer',
    purpose: 'Kiểm tra chính tả, giọng thương hiệu, CTA, đường dẫn, thông tin kỹ thuật và rủi ro nội dung.',
    inputs: ['Toàn bộ phiên bản bài', 'Creative brief', 'Brand rules', 'Danh sách từ cấm'],
    outputs: ['QA report', 'Điểm chất lượng', 'Danh sách cần sửa', 'Trạng thái đạt/chưa đạt'],
    gate: 'Chỉ nội dung đạt QA mới được chuyển sang duyệt.',
  },
  {
    id: 'approval',
    order: 7,
    name: 'Phê duyệt',
    agent: 'Human Approver',
    purpose: 'Con người quyết định nội dung được phép xuất bản và chịu trách nhiệm cuối cùng.',
    inputs: ['Nội dung đã QA', 'Media hoàn chỉnh', 'Lịch dự kiến'],
    outputs: ['Đã duyệt', 'Yêu cầu sửa', 'Từ chối', 'Ghi chú phê duyệt'],
    gate: 'Không có phê duyệt thì không được đăng tự động.',
  },
  {
    id: 'publish',
    order: 8,
    name: 'Lập lịch & phân phối',
    agent: 'AI Publishing Operator',
    purpose: 'Đưa bài đã duyệt vào đúng kênh, đúng thời gian và theo dõi trạng thái xuất bản.',
    inputs: ['Bài đã duyệt', 'Tài khoản kết nối', 'Thời gian đăng', 'Quy tắc retry'],
    outputs: ['Publishing job', 'Platform result', 'Retry record', 'Dead-letter record'],
    gate: 'Preflight phải đạt trước khi gọi API nền tảng.',
  },
  {
    id: 'analytics',
    order: 9,
    name: 'Đo lường & học lại',
    agent: 'AI Performance Analyst',
    purpose: 'Đánh giá kết quả, tìm nội dung hiệu quả và cập nhật quy tắc cho chiến dịch sau.',
    inputs: ['Chỉ số nền tảng', 'KPI chiến dịch', 'Lịch sử bài', 'Phản hồi khách hàng'],
    outputs: ['Performance report', 'Bài học', 'Đề xuất thử nghiệm', 'Cập nhật brand memory'],
    gate: 'Không tối ưu chỉ dựa trên một chỉ số đơn lẻ.',
  },
];

export const AI_ROUTING_RULES = {
  defaultProvider: 'gemini',
  fallbackProvider: 'ollama',
  humanApprovalRequired: true,
  publishOnlyApproved: true,
  maxRevisionRounds: 3,
  principles: [
    'Một agent chỉ chịu trách nhiệm chính cho một loại quyết định.',
    'Dữ liệu và điều phối workflow nằm ngoài prompt để dễ kiểm soát.',
    'Mọi đầu ra phải có cấu trúc và trạng thái rõ ràng.',
    'Không để AI tự xuất bản khi chưa qua QA và phê duyệt.',
    'Không lưu khóa API hoặc token nền tảng trong prompt hay trình duyệt công khai.',
  ],
};
