export const PERSISTENT_PLATFORM_CONNECTIONS = Object.freeze([
  {
    id: 'linkedin',
    label: 'LinkedIn',
    tokenLabel: 'OAuth Access Token',
    tokenPlaceholder: 'Dán access token có quyền đăng bài',
    targetKey: 'authorUrn',
    targetLabel: 'Author URN',
    targetPlaceholder: 'urn:li:person:... hoặc urn:li:organization:...',
    portal: { label: 'Mở LinkedIn Developer Apps', href: 'https://www.linkedin.com/developers/apps' },
    tokenHelp: { label: 'Tạo access token', href: 'https://www.linkedin.com/developers/tools/oauth/token-generator' },
    targetHelp: { label: 'Hướng dẫn Author URN', href: 'https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/posts-api' },
    docs: { label: 'Tài liệu OAuth chính thức', href: 'https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow' },
    steps: [
      'Tạo hoặc chọn ứng dụng trong LinkedIn Developer Portal và liên kết LinkedIn Page nếu đăng với tư cách tổ chức.',
      'Cấp sản phẩm/quyền phù hợp (ví dụ w_member_social hoặc quyền tổ chức được LinkedIn phê duyệt), rồi tạo OAuth access token.',
      'Dán token và đúng Author URN. Worker sẽ đối chiếu tài khoản với LinkedIn trước khi cho phép xếp lịch.',
    ],
  },
  {
    id: 'pinterest',
    label: 'Pinterest',
    tokenLabel: 'OAuth Access Token',
    tokenPlaceholder: 'Dán Pinterest access token',
    targetKey: 'boardId',
    targetLabel: 'Board ID',
    targetPlaceholder: 'Ví dụ: 123456789012345678',
    portal: { label: 'Mở Pinterest Apps', href: 'https://developers.pinterest.com/apps/' },
    tokenHelp: { label: 'Thiết lập OAuth token', href: 'https://developers.pinterest.com/docs/getting-started/set-up-authentication-and-authorization/' },
    targetHelp: { label: 'Tra Board ID', href: 'https://developers.pinterest.com/docs/api/v5/boards-list/' },
    docs: { label: 'Kết nối Pinterest App', href: 'https://developers.pinterest.com/docs/getting-started/connect-app/' },
    steps: [
      'Đăng ký Pinterest Business App và chờ Trial/Standard access theo quy trình chính thức.',
      'Hoàn tất OAuth với scope boards:read và pins:write; token thử nghiệm có thể hết hạn sau 24 giờ.',
      'Lấy Board ID bằng endpoint danh sách board, rồi dán token và Board ID của cùng tài khoản.',
    ],
  },
  {
    id: 'youtube',
    label: 'YouTube / Shorts',
    tokenLabel: 'OAuth 2.0 Access Token',
    tokenPlaceholder: 'Dán token có scope youtube.upload',
    targetKey: 'channelId',
    targetLabel: 'YouTube Channel ID',
    targetPlaceholder: 'UCxxxxxxxxxxxxxxxxxxxxxx',
    portal: { label: 'Mở Google Cloud Credentials', href: 'https://console.cloud.google.com/apis/credentials' },
    tokenHelp: { label: 'Hướng dẫn OAuth YouTube', href: 'https://developers.google.com/youtube/v3/guides/auth/server-side-web-apps' },
    targetHelp: { label: 'Tra Channel ID', href: 'https://developers.google.com/youtube/v3/docs/channels/list' },
    docs: { label: 'Tài liệu upload video', href: 'https://developers.google.com/youtube/v3/docs/videos/insert' },
    steps: [
      'Tạo Google Cloud project, bật YouTube Data API v3 và cấu hình OAuth consent/credentials.',
      'Ủy quyền scope https://www.googleapis.com/auth/youtube.upload cho đúng kênh cần đăng.',
      'Lấy Channel ID bằng channels.list với mine=true, rồi dán token và Channel ID. Upload mặc định private để kiểm thử an toàn.',
    ],
  },
]);
